### ISSUE TITLE
차용증 작성하기 화면

### ISSUE THREAD

**Issue by wjdwntjd55** [AlltimeOwl/PayRit-Android#10]
### Todo

- [x] 차용증 작성하기 화면
- [x] 거래 내역 작성하기 화면
- [x] 내 정보 작성하기 화면
- [x] 상대방 정보 작성하기 화면
- [x] 차용증 내용 확인 화면
- [x] 차용증 작성시 서버와 연결
