### ISSUE TITLE
페이릿 상세 페이지 화면

### ISSUE THREAD

**Issue by wjdwntjd55** [AlltimeOwl/PayRit-Android#12]
### Todo

- [x] 페이릿 상세 페이지 화면
- [x] 돈 빌려준 사람이 보는 페이릿 상세 페이지를 서버와 연결
- [x] 돈 빌려준 사람이 보는 페이릿 상세 페이지에 있는 PDF 내용을 서버와 연결
- [x] 돈 빌린 사람이 보는 페이릿 상세 페이지를 서버와 연결
- [x] 돈 빌린 사람이 보는 페이릿 상세 페이지에 있는 PDF 내용을 서버와 연결
- [x] 돈 빌려준 사람이 보는 페이릿 상세 페이지에 있는 일부 상환하기 기능 구현
- [x] 돈 빌려준 사람이 보는 페이릿 상세 페이지에 있는 전체 상환하기 기능 구현
- [x] 돈 빌려준 사람이 보는 페이시 상세 페이지에 있는 메모입력하는 기능 구현
- [x] 돈 빌려준 사람이 입력한 메모 목록 조회 기능 구현
- [x] 메모 삭제하는 기능 구현
