### ISSUE TITLE
홈 화면 구현

### ISSUE THREAD

**Issue by wjdwntjd55** [AlltimeOwl/PayRit-Android#3]
### Todo

- [x] 홈 화면 UI 구현
- [x] 홈 화면에 서버와 연결해서 차용증 리스트 보여주기
- [x] 차용증 받은 유저가 차용증 내용 확인하는 화면을 서버와 연결해서 구현
- [x] 차용증 받은 유저가 차용증 수락하는 기능
